# Generated by Django 3.0.3 on 2022-05-20 23:20

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100)),
                ('region_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstatePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('image_url', models.ImageField(blank=True, default=None, null=True, upload_to=api.models.upload_to)),
                ('contact_phone_number', models.CharField(max_length=12)),
                ('area_by_m2', models.CharField(max_length=10)),
                ('width_of_facade', models.IntegerField()),
                ('width_of_road', models.IntegerField()),
                ('direction', models.CharField(choices=[('North', 'North'), ('East', 'East'), ('South', 'South'), ('West', 'West')], max_length=15)),
                ('is_legal', models.BooleanField(default=False)),
                ('price', models.CharField(max_length=10)),
                ('rank', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_posts', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_posts', to='api.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=255)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('realEstatePost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.RealEstatePost')),
            ],
        ),
    ]
