# Generated by Django 3.0.3 on 2022-06-02 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220522_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realestatepost',
            options={'get_latest_by': ['id']},
        ),
    ]
