# Generated by Django 3.0.3 on 2022-07-17 02:12

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20220602_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.CharField(max_length=200)),
                ('expiry_date', models.CharField(max_length=200)),
                ('type_post', models.CharField(max_length=100)),
                ('code_post', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(blank=True, default=None, null=True, upload_to=api.models.upload_to)),
                ('image_2', models.ImageField(blank=True, default=None, null=True, upload_to=api.models.upload_to)),
                ('image_3', models.ImageField(blank=True, default=None, null=True, upload_to=api.models.upload_to)),
                ('image_4', models.ImageField(blank=True, default=None, null=True, upload_to=api.models.upload_to)),
                ('image_5', models.ImageField(blank=True, default=None, null=True, upload_to=api.models.upload_to)),
                ('image_6', models.ImageField(blank=True, default=None, null=True, upload_to=api.models.upload_to)),
                ('image_7', models.ImageField(blank=True, default=None, null=True, upload_to=api.models.upload_to)),
                ('image_8', models.ImageField(blank=True, default=None, null=True, upload_to=api.models.upload_to)),
                ('image_9', models.ImageField(blank=True, default=None, null=True, upload_to=api.models.upload_to)),
                ('image_10', models.ImageField(blank=True, default=None, null=True, upload_to=api.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='SimilarRealestatePostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId_1', models.IntegerField()),
                ('postId_2', models.IntegerField()),
                ('postId_3', models.IntegerField()),
                ('postId_4', models.IntegerField()),
                ('postId_5', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('price', models.CharField(max_length=100)),
                ('mat_tien', models.FloatField()),
                ('huong_nha', models.CharField(max_length=200)),
                ('duong_vao', models.FloatField(default=0.0)),
                ('bedroom_number', models.IntegerField()),
                ('toilet_number', models.IntegerField()),
                ('phap_ly', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='realestatepost',
            options={},
        ),
        migrations.AlterField(
            model_name='region',
            name='region_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='RealEstatePost2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(max_length=2000)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('rank', models.IntegerField(default=1)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_post2s', to='api.Config')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_post2s', to=settings.AUTH_USER_MODEL)),
                ('images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_post2s', to='api.Image')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_post2s', to='api.Region')),
                ('similar_posts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_post2s', to='api.SimilarRealestatePostList')),
                ('spec_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_post2s', to='api.SpecDetail')),
            ],
        ),
    ]
