# Generated by Django 3.0.3 on 2022-07-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220717_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specdetail',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specdetail',
            name='bedroom_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specdetail',
            name='huong_nha',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='specdetail',
            name='mat_tien',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specdetail',
            name='phap_ly',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='specdetail',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specdetail',
            name='toilet_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
