# Generated by Django 3.0.3 on 2022-08-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_extendeduserinfomation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedRealestateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_list_str', models.CharField(max_length=1000)),
            ],
        ),
    ]
