# Generated by Django 3.0.3 on 2022-08-11 23:39

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_reportedrealestatelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_1', models.FileField(blank=True, default=None, null=True, upload_to=api.models.video_upload_to)),
                ('video_2', models.FileField(blank=True, default=None, null=True, upload_to=api.models.video_upload_to)),
                ('video_3', models.FileField(blank=True, default=None, null=True, upload_to=api.models.video_upload_to)),
                ('video_4', models.FileField(blank=True, default=None, null=True, upload_to=api.models.video_upload_to)),
                ('video_5', models.FileField(blank=True, default=None, null=True, upload_to=api.models.video_upload_to)),
            ],
        ),
        migrations.AddField(
            model_name='realestatepost2',
            name='videos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_post2s', to='api.Video'),
        ),
    ]
