# Generated by Django 3.0.3 on 2022-06-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20220611_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='color_code',
            field=models.CharField(max_length=2, null=True, unique=True),
        ),
    ]
