# Generated by Django 3.0.3 on 2022-07-09 16:01

from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_region_color_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_url',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='post',
            name='image_10',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=forum.models.upload_to),
        ),
        migrations.AddField(
            model_name='post',
            name='image_2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=forum.models.upload_to),
        ),
        migrations.AddField(
            model_name='post',
            name='image_3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=forum.models.upload_to),
        ),
        migrations.AddField(
            model_name='post',
            name='image_4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=forum.models.upload_to),
        ),
        migrations.AddField(
            model_name='post',
            name='image_5',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=forum.models.upload_to),
        ),
        migrations.AddField(
            model_name='post',
            name='image_6',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=forum.models.upload_to),
        ),
        migrations.AddField(
            model_name='post',
            name='image_7',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=forum.models.upload_to),
        ),
        migrations.AddField(
            model_name='post',
            name='image_8',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=forum.models.upload_to),
        ),
        migrations.AddField(
            model_name='post',
            name='image_9',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=forum.models.upload_to),
        ),
    ]
