# Generated by Django 3.0.3 on 2022-07-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20220709_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('SELL', 'SELL'), ('RENT', 'LEASE')], default=None, max_length=100, null=True),
        ),
    ]
